// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tufatperrzjxceuvhjqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZmF0cGVycnpqeGNldXZoanFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjU5MTAsImV4cCI6MjA2MzY0MTkxMH0.QBkE0dtYv4URLH0vGykDAHA_JVjuP4Lqzxa7MXFmcM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);